### ISSUE TITLE
Add Google Analytics code to the header if the organization entity has a valid value

### ISSUE THREAD

**Issue by deshetti** [factly/dega-web#101]
If the organization entity from dega-api has a non-empty value for GATracking code, we need to add Google Analytics code to the header.

This should be available on all pages, to have Google Analytics enabled for the site.

Reference: https://support.google.com/analytics/answer/1008080?hl=en

**Comment by KriAga** [comment]
This issue has been handled in this PR. https://github.com/factly/dega-web/pull/152

**Comment by KriAga** [comment]
https://github.com/factly/dega-web/pull/152
