### ISSUE TITLE
Create a sitemap map for the site

### ISSUE THREAD

**Issue by deshetti** [factly/dega-web#102]
Reference: Use the following nuxt module: https://github.com/nuxt-community/sitemap-module
About sitemap: https://www.sitemaps.org/index.html

The issue is dependent on the following issue in dega-api to generate the sitemap links: https://github.com/factly/dega-api/issues/17

- [ ] Create sitemap.xml with dummy urls with the following parent urls:
http://factcheck.factly.in/post-sitemap.xml like in https://factly.in/post-sitemap1.xml
http://factcheck.factly.in/factcheck-sitemap.xml like in https://factly.in/post-sitemap1.xml
http://factcheck.factly.in/author-sitemap.xml like in https://factly.in/author-sitemap.xml
http://factcheck.fatly.in/category-sitemap.xml like in https://factly.in/category-sitemap.xml
http://factcheck.fatly.in/tag-sitemap.xml like in https://factly.in/category-sitemap.xml
http://factcheck.fatly.in/media-sitemap.xml like in https://factly.in/attachment-sitemap1.xml
- [ ] Integrate the sitemap api from dega-api

**Comment by KriAga** [comment]
The nuxt module adds only the static links to the sitemap page. This has been implemented and added in PR https://github.com/factly/dega-web/pull/111
