### ISSUE TITLE
Fact description is not on the same line in ClaimWidget component

### ISSUE THREAD

**Issue by KriAga** [factly/dega-web#145]
Right now, the Fact description is being added using v-html directive so it adds a p-tag and hence shifts the description on the next line.
This issue is in reference to https://github.com/factly/dega-web/issues/142

![image](https://user-images.githubusercontent.com/20995709/58115841-94432b00-7c18-11e9-8a6f-639e526c708f.png)

**Comment by dmonark** [comment]
PR - md-claim-widget
New claim widget has been added 
Done
