### ISSUE TITLE
Multiple authors doesn't show in the correct format

### ISSUE THREAD

**Issue by deshetti** [factly/dega-web#194]
I mentioned to @monarkatfactly that stories with multiple authors should display in the following format: https://theintercept.com/2019/05/29/nsa-sidtoday-surveillance-intelligence/

Currently it is showing all the images in multiple lines and the author names in multiple lines as well. https://factcheck.factly.in/factcheck/how-true-are-government-claims-about-the-pradhan-mantri-matru-vandana-yojana

**Comment by dmonark** [comment]
How to test this? which client has multiple author article?

**Comment by dmonark** [comment]
By adding `is-grouped` class with `field` we can resolve this issue.
