### ISSUE TITLE
Cleanup the factcheck rating widget

### ISSUE THREAD

**Issue by deshetti** [factly/dega-web#33]
- [x] Remove the boundaries of the rating images
- [x] cleanup the white spaces around the widget
- [x] cleanup the font sizes

have it look something similar to the widgets in this page: https://medium.com/google-cloud/installing-helm-in-google-kubernetes-engine-7f07f43c536e

**Comment by KriAga** [comment]
I have removed some padding from the images in https://github.com/factly/dega-web/pull/41

As we have given a class of box type to each claim, there is a lot of space left. On removing that the page is becoming clumsy so did not remove it. would look at some other workaround for this.

**Comment by KriAga** [comment]
Adding review made the claims section look more filled up. https://github.com/factly/dega-web/pull/52/commits/88067eb3ab31b73b7741276599fb349fa90e0312

**Comment by deshetti** [comment]
Cleaned up the claim widget but there a quite a few things pending and added another issue to track the same: https://github.com/factly/dega-web/issues/75

Closing this now as a duplicate.
