### ISSUE TITLE
Collapse About us on Mobile view

### ISSUE THREAD

**Issue by deshetti** [factly/dega-web#34]

**Comment by KriAga** [comment]
This is still an open issue in Bulma.
https://github.com/jgthms/bulma/issues/1567#issue-284766970

**Comment by deshetti** [comment]
@KriAga can you please check the temporary workaround @tanmay-das mentioned in the thread: https://codepen.io/tanmaydas/pen/dKbBQK

**Comment by KriAga** [comment]
It is a js solution and would work when clicked so can not use it for mobile until we remove the link to another page from about-us.

**Comment by KriAga** [comment]
https://github.com/factly/dega-web/pull/43
