### ISSUE TITLE
Add Authors Image for stories

### ISSUE THREAD

**Issue by KriAga** [factly/dega-web#74]
- [ ] Post-detail page
- [ ] Factcheck-detail page

Use Bulma's rounded-image for the author image: https://bulma.io/documentation/elements/image/

**Comment by dmonark** [comment]
PR - MD-claim-widget 
Done

**Comment by deshetti** [comment]
@monarkatfactly  You closed the issue, but I don't see that this is implemented.

**Comment by dmonark** [comment]
I have resolved this issue in md-claim-widget branch (merged with develop)

**Comment by deshetti** [comment]
@monarkatfactly my bad, i see it. the one's I checked did not have images in gateway.
