### ISSUE TITLE
Changes to the Claim widget in the factcheck details page

### ISSUE THREAD

**Issue by deshetti** [factly/dega-web#75]
- [x] Fix the desktop view
- [x] Fix the tablet view (probably create a new widget for tablet view)
- [x] Fix the mobile view (probably create a new widget for mobile view)
- [x] Link the 'claimed by' widget title to the claim source
- [x] Add social sharing buttons to the widget
- [x] Show the date on the claim widget title only when the claim date is not null

**Comment by KriAga** [comment]
Tablet view is having some duplicate elements


![image](https://user-images.githubusercontent.com/20995709/58903261-9205c400-8722-11e9-88ad-4547799939b2.png)
